version: '2'
services:

  php:
    container_name: sa-php
    image: php:7-fpm
    volumes:
        - .:/var/www/site

  nginx:
    container_name: sa-nginx
    image: nginx:stable
    volumes:
        - .:/var/www/site
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
    ports:
        - "8080:80"

  gulp:
    restart: on-failure
    container_name: sa-gulp
    build: docker/gulp
    volumes:
        - .:/var/www/site
