version: '2'
services:

  php:
    image: php:7-fpm
    volumes:
        - .:/var/www/site

  nginx:
    image: nginx:stable
    volumes:
        - .:/var/www/site
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
    ports:
       - "8080:80"

  tools:
    build: docker/tools
    links:
        - php    
    volumes_from:
        -  php
